name: Autofixers

on: [pull_request_review]

jobs:
  precommit:
    name: Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source for the PR
        run: git clone --branch="$GITHUB_BRANCH" "https://github.com/${GITHUB_REPO}" . && git reset --hard "$GITHUB_REV"
        env:
          GITHUB_REV: ${{ github.event.pull_request.head.sha }}
          GITHUB_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_REPO: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install brew
        run: |
          HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew
          sudo mkdir -p /home/linuxbrew
          sudo git clone https://github.com/Homebrew/brew "$HOMEBREW_REPOSITORY"
          sudo mkdir -p "$HOMEBREW_REPOSITORY/Library/Taps/homebrew"
          sudo ln -s "$PWD" "$HOMEBREW_REPOSITORY/Library/Taps/homebrew/homebrew-formula-analytics"
          sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
          export PATH="/home/linuxbrew/.linuxbrew/bin:/usr/local/bin:$PATH"
          echo ::set-env name=PATH::$PATH
      - name: Install Deps
        run: |
          brew install pre-commit terraform-docs terraform
      - name: Terraform init
        uses: hashicorp/terraform-github-actions/init@v0.4.0
      - name: Run pre-commit
        run: |
          pre-commit run --show-diff-on-failure --all-files
      - name: Auto-commit changes, if any
        if: contains(github.event.review.body, '/fix') && failure()
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply pre-commit fixes
          branch: ${{ github.event.pull_request.head.ref }}
        env:
          # If the default GitHub Provided token is used then a new
          #  check run will not be triggered. This is bad because
          #  checks are required for merging.
          # A workaround is to use a personal token.
          #  Ugly, but eh. Fixes it
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
